// Code generated by "stringer -type NodeKind"; DO NOT EDIT.

package fswiki

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NodeUnknown-0]
	_ = x[NodeHeadingOpen-1]
	_ = x[NodeHeadingClose-2]
	_ = x[NodeUnorderedListOpen-3]
	_ = x[NodeUnorderedListClose-4]
	_ = x[NodeOrderedListOpen-5]
	_ = x[NodeOrderedListClose-6]
	_ = x[NodeListItemOpen-7]
	_ = x[NodeListItemClose-8]
	_ = x[NodeParagraphOpen-9]
	_ = x[NodeParagraphClose-10]
	_ = x[NodePreformatted-11]
	_ = x[NodeTableOpen-12]
	_ = x[NodeTableClose-13]
	_ = x[NodeTableHeaderOpen-14]
	_ = x[NodeTableHeaderClose-15]
	_ = x[NodeTableRowOpen-16]
	_ = x[NodeTableRowClose-17]
	_ = x[NodeTableDataOpen-18]
	_ = x[NodeTableDataClose-19]
	_ = x[NodeStrongOpen-20]
	_ = x[NodeStrongClose-21]
	_ = x[NodeEMOpen-22]
	_ = x[NodeEMClose-23]
	_ = x[NodeInline-24]
	_ = x[NodeText-25]
	_ = x[NodeSoftBreak-26]
	_ = x[NodeComment-27]
	_ = x[NodePlugin-28]
}

const _NodeKind_name = "NodeUnknownNodeHeadingOpenNodeHeadingCloseNodeUnorderedListOpenNodeUnorderedListCloseNodeOrderedListOpenNodeOrderedListCloseNodeListItemOpenNodeListItemCloseNodeParagraphOpenNodeParagraphCloseNodePreformattedNodeTableOpenNodeTableCloseNodeTableHeaderOpenNodeTableHeaderCloseNodeTableRowOpenNodeTableRowCloseNodeTableDataOpenNodeTableDataCloseNodeStrongOpenNodeStrongCloseNodeEMOpenNodeEMCloseNodeInlineNodeTextNodeSoftBreakNodeCommentNodePlugin"

var _NodeKind_index = [...]uint16{0, 11, 26, 42, 63, 85, 104, 124, 140, 157, 174, 192, 208, 221, 235, 254, 274, 290, 307, 324, 342, 356, 371, 381, 392, 402, 410, 423, 434, 444}

func (i NodeKind) String() string {
	if i < 0 || i >= NodeKind(len(_NodeKind_index)-1) {
		return "NodeKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NodeKind_name[_NodeKind_index[i]:_NodeKind_index[i+1]]
}
