name: test
on: push
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go: ['1.20']
    runs-on: ${{ matrix.os }}
    steps:
      -
        name: Clone repository
        uses: actions/checkout@v3
      -
        name : Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
          cache: true
      - 
        name: Run Test
        run: |
          go test -v ./...
